---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: restart nginx

- name: Ensure nginx is enabled and started
  service:
    name: nginx
    state: started
    enabled: yes
